<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Financiera.Data\Financiera.Data.csproj" />
    <ProjectReference Include="..\Financiera.Entities\Financiera.Entities.csproj" />
  </ItemGroup>

</Project>
